In [8]:
import tensorflow as tf
import numpy as np

data = np.random.randint(1,100,[5,5])
print("== original ==")
print(data)

num_example=data.shape[0]
arr=np.arange(num_example)
np.random.shuffle(arr)
data=data[arr]
print("== shuffled ==")
print(data)

ratio=0.8
s=np.int(num_example*ratio)
x_train=data[:s]
x_val=data[s:]
print("== x_train ==")
print(x_train)
print("== x_val ==")
print(x_val)



== original ==
[[ 5 77 26  4 51]
 [11 27 42 95  9]
 [20 18 74 58 76]
 [15 44 13 20 61]
 [48 96 99 75 49]]
== shuffled ==
[[ 5 77 26  4 51]
 [48 96 99 75 49]
 [11 27 42 95  9]
 [20 18 74 58 76]
 [15 44 13 20 61]]
== x_train ==
[[ 5 77 26  4 51]
 [48 96 99 75 49]
 [11 27 42 95  9]
 [20 18 74 58 76]]
== x_val ==
[[15 44 13 20 61]]
